version: '3'
services:
  app:
    entrypoint: python3 main.py
    environment:
      - LD_LIBRARY_PATH=.../**/torch/lib
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./audio:/app/audio
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./main.py:/app/main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
